easy_admin:
    site_name: HR System
    user:
        display_name: true
        display_avatar: true
        name_property_path: 'fullName'
    design:
        assets:
            css:
                - 'css/admin.css'
            favicon: '/assets/img/favicon.ico'
        menu:
            - { route: 'homepage', label: 'Вернуться на сайт', icon: 'home' }
            - { entity: 'User', label: 'Пользователи', icon: 'user' }
            - { entity: 'Vacancy', label: 'Вакансии' }
            - { entity: 'Group', label: 'Группы вакансий'}
    entities:
        User:
            class: App\Entity\User
            label: 'Пользователи'
            form:
                title: 'Добавление пользователя'
                fields:
                    - { property: 'firstName', label: 'Имя' }
                    - { property: 'secondName', label: 'Фамилия' }
                    - { property: 'patronymic', label: 'Отчество'}
                    - { property: 'email', type: 'email', label: 'Электронная почта' }
                    - { property: 'phone', label: 'Номер телефона' }
                    - { property: 'username', label: 'Логин' }
                    - { property: 'plainPassword', label: 'Пароль', type: 'password' }
                    - { property: 'userRoles', label: 'Роли', type_options: {'by_reference': false} }
            search:
                fields: [ 'firstName', 'secondName', 'phone' ]
            list:
                fields:
                    - { property: 'fullName', label: 'ФИО' }
                    - { property: 'email', type: 'email', label: 'Электронная почта' }
                    - { property: 'phone', label: 'Номер телефона' }
                    - { property: 'username', label: 'Логин' }
            edit:
                title: 'Редактирования пользователя'

        Vacancy:
            class: App\Entity\Vacancy
            controller: App\Controller\Admin\VacancyController
            label: 'Ваканасии'
            form:
                title: 'Добавление вакансии'
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'groups', label: 'Группы', type_options: {'by_reference': false} }
                    - { property: 'hrs', label: 'Кому доступна вакансия', type_options: {'by_reference': false} }
            search:
                fields: [ 'name' ]
            list:
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'groups', label: 'Группы' }
                    - { property: 'hrs', label: 'Кому доступна вакансия' }
            edit:
                title: 'Редактирования вакансии'

        Group:
            class: App\Entity\Group
            controller: App\Controller\Admin\GroupController
            label: 'Группы вакансий'
            form:
                title: 'Добавление группы'
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'vacancies', label: 'Вакансии', type_options: {'by_reference': false} }
                    - { property: 'hrs', label: 'Кому доступна вакансия' }
            search:
                fields: [ 'name' ]
            list:
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'vacancies', label: 'Вакансии' }
                    - { property: 'hrs', label: 'Кому доступна вакансия' }
            edit:
                title: 'Редактирования вакансии'
